---
project:
  type: website
  title: "rrutherford4"
  output-dir: public_html
  post-render:
    - cp public_html/README.md ./README.md

format:
  html:
    theme:
      light: flatly
      dark: darkly
    default: true
    toc: true
    toc-depth: 4

website:
  repo-url: https://github.com/cameronrutherford/rrutherford4
  repo-actions: [edit, source, issue]
  search:
    type: overlay

  navbar:
    search: true
    left:
      - text: "Classes"
        menu:
          - text: "CISC2200 - Fall 24"
            href: class/cisc2200-fall24/index.qmd
      - text: "How To Guides"
        menu:
          - howto/vscode.qmd
          - howto/docker.qmd
      - text: "Site Dev Guide"
        menu:
          - about.qmd
    tools:
      - icon: github
        href: https://github.com/cameronrutherford
        text: Quarto GitHub
      - icon: linkedin
        href: https://www.linkedin.com/in/robert-c-rutherford/
        text: LinkedIn

  sidebar:
    - id: cisc2200-fall24
      title: "CISC2200 - Fall 24"
      style: "floating"
      collapse-level: 1
      align: left
      contents:
        - class/cisc2200-fall24/index.qmd
        - class/cisc2200-fall24/schedule.qmd
        - class/cisc2200-fall24/resources.qmd
