---
title: "About"
format:
  html:
    default: true
    toc: true
    toc-depth: 4
  gfm:
    default: true
    toc: true
    output-ext: md
    output-file: README
---

This repo will mainly focus on the home page for me and the courses I teach.

It's written in Quarto, with CI maintained by GitHub.

## Structure

While not sticking to it explicitly, I will try and follow [diataxis](https://diataxis.fr)
as a principle.

### Developer Guide

Information related to how I maintain these docs with CI, and how you could DIY.

- [This page](./about.qmd)

### How-Tos

Since there will hopefully eventually be some shared information re-used across
classes, I will store some general useful advice and How-Tos here.

- [VSCode](./howto/vscode.qmd)
- [Docker](./howto/docker.qmd)

### HomePage

About me, and links to things like GoogleScholar, LinkedIn, GitHub and more...

If I ever make explanation that is independent of a class, it will go here.

Will include a RevealJS presentation!

### Classes (Tutorials)

Links will lead on the page will lead to:

- Lecture materials (on GitHub or otherwise)
- Syllabus
- Calendar invites
- Code repositories
- Blackboard and other resources

#### Fall '24 CISC 2200

Basic HomePage with all the links and material referenced and hosted.

- [https://github.com/CISC2200-Fall-24-Fordham](https://github.com/CISC2200-Fall-24-Fordham)

