---
title: "Schedule"
format:
  html:
    default: true
    toc: true
    toc-depth: 3

---

Each lecture / class session will have it's own page, a summary will be given here.

If anything is marked as due on a given day, it is due at 11:59pm EST that day unless otherwise stated.

## 08/28

### Content

- [Professor Introduction](./../../index.qmd)
- [Course Intro Slides](https://docs.google.com/presentation/d/1rGrOyCqNu3fuqEOVQof8Dk1ufRul9YhX/edit?usp=sharing&ouid=115990634876478916795&rtpof=true&sd=true)
- [Course Syllabus](./index.qmd)
- [Course Resources](./resources.qmd)
- [Survey 1](https://forms.gle/bRdYNR2sxHpkUs3P9)

#### Optional Content

- [Developing Inside a Container](https://code.visualstudio.com/docs/devcontainers/containers)
- [Try Development Containers: C++](https://github.com/microsoft/vscode-remote-try-cpp)

### Project

- [Project: Simple Expression Evaluator Overview](https://docs.google.com/presentation/d/19jkySeLhxxQ9n7AQXN3KEHtNo26_Grhy/edit?usp=sharing&ouid=115990634876478916795&rtpof=true&sd=true)
  - [Part 1 Instructions](https://cisc2200.github.io/proj-part1/)
  - [Part 2 Instructions](https://cisc2200.github.io/proj-part2/)
  - [Part 3 Instructions](https://cisc2200.github.io/proj-part3/)

### Due

#### Next Session / Upcoming

- [Lab 1: IntArray](https://github.com/CISC2200-Fall-24-Fordham/Lab1) - due 09/18
  - Ensure that you can clone / compile / run the project
- Quiz 1: 09/16

## **LABOR DAY**

## 09/04

- Classes follow a Monday schedule...

### Content

- [Office Hours Poll](https://doodle.com/meeting/participate/id/aKmYq0Gd)
- [CPP Review](https://docs.google.com/presentation/d/1_DKSzRcnKmUTTQOVoL5a3EpjQHVDAN-Q/edit?usp=sharing&ouid=115990634876478916795&rtpof=true&sd=true)
- CS2 Review
  - [Friendship and inheritance](https://cplusplus.com/doc/tutorial/inheritance/)
  - [Polymorphism](https://cplusplus.com/doc/tutorial/polymorphism/)
  - [std::sort / iteration protocols](https://en.cppreference.com/w/cpp/algorithm/sort)
- In-class Lab: [CS2 Review Coding Exercise](https://github.com/CISC2200-Fall-24-Fordham/CS2-Review)

### Due

#### Next Session / Upcoming

- **Tomorrow** is the last day to drop/add a class. Choose wisely...
- [Lab 1: IntArray](https://github.com/CISC2200-Fall-24-Fordham/Lab1) - due 09/18
- 09/06: Syllabi are due to the dean's office
- Quiz 1: 09/16
  - [Quiz 1 Study Guide](https://docs.google.com/document/d/1hzwxkHhTrzqFQrr6YJNpGAaOq11AjvNoqIYvWn3NaEI/edit?usp=sharing)

## 09/09

### Content

- Wrap-up In-class Lab: [CS2 Review Coding Exercise](https://github.com/CISC2200-Fall-24-Fordham/CS2-Review)
  - [Printing Colored Text](https://www.geeksforgeeks.org/how-to-print-colored-text-in-c/)
- [Pointers, references and IntList Slides](https://docs.google.com/presentation/d/1k97kFssH5m_XeCKtOZoaFU41pCYSyP9z/edit?usp=sharing&ouid=115990634876478916795&rtpof=true&sd=true)
  - [NULL vs. nullptr](https://stackoverflow.com/questions/36484473/is-c-null-equal-to-c11-nullptr)
- [IntList Sample Code](https://github.com/CISC2200-Fall-24-Fordham/IntList)
- Quiz 1 review
  - [Quiz 1 Study Guide](https://docs.google.com/document/d/1hzwxkHhTrzqFQrr6YJNpGAaOq11AjvNoqIYvWn3NaEI/edit?usp=sharing)

### Due

#### Next Session / Upcoming

- [Lab 1: IntArray](https://github.com/CISC2200-Fall-24-Fordham/Lab1) - due 09/18
- Quiz 1: 09/16
  - [Quiz 1 Study Guide](https://docs.google.com/document/d/1hzwxkHhTrzqFQrr6YJNpGAaOq11AjvNoqIYvWn3NaEI/edit?usp=sharing)

## 09/11

### Content

- [ADT IntList Slides](https://docs.google.com/presentation/d/18ioi-LNuQuZwa5D-GVoD6a9J9fisvGBV/edit?usp=sharing&ouid=115990634876478916795&rtpof=true&sd=true)
  - [IntList Sample Code - UPDATED](https://github.com/CISC2200-Fall-24-Fordham/IntList)
- Quiz 1 review
  - [Quiz 1 Study Guide](https://docs.google.com/document/d/1hzwxkHhTrzqFQrr6YJNpGAaOq11AjvNoqIYvWn3NaEI/edit?usp=sharing)
  - [Quiz 1 Review and Further Reading](https://docs.google.com/document/d/1TRiqVw-4abvVl-3sNkf00gqPXnRiiRj8E_G8MeCHLS0/edit?usp=sharing)
- Making things pretty
  - [std::format](https://en.cppreference.com/w/cpp/utility/format/format) - I might cover color printing later...
  - [VSCode Themes](https://code.visualstudio.com/docs/getstarted/themes)
  - [Linux, The Terminal, and Oh-My-Bash](./../../howto/shell.qmd)

### Bonus Content

- Suggested Reading:
  - [Recursion Over Lists YouTube video](https://youtu.be/0y325A82vMc)
  - [How Not to Teach Recursion](https://parentheticallyspeaking.org/articles/how-not-to-teach-recursion/)
  - [Makefile Tutorial](https://makefiletutorial.com/)

### Due

#### Next Session / Upcoming

- 09/13: Round 1 attendance reports due
- [Lab 1: IntArray](https://github.com/CISC2200-Fall-24-Fordham/Lab1) - due 09/18
- Quiz 1: 09/16
  - [Quiz 1 Study Guide](https://docs.google.com/document/d/1hzwxkHhTrzqFQrr6YJNpGAaOq11AjvNoqIYvWn3NaEI/edit?usp=sharing)

## 09/16

### Content

- **QUIZ 1** given in class
  - [Quiz 1 Study Guide](https://docs.google.com/document/d/1hzwxkHhTrzqFQrr6YJNpGAaOq11AjvNoqIYvWn3NaEI/edit?usp=sharing)

### Due

#### Next Session / Upcoming

- [Lab 1: IntArray](https://github.com/CISC2200-Fall-24-Fordham/Lab1) - due 09/18

## 09/18

### Content

- Lab 1 questions / C++ standard clarification
  - Lab1 only supports c++11
  - I will enable c++20 support moving fowrard (I hope)
- Quiz 1 Review: Test Corrections - next time!
- [Singly Linked List Slides](https://docs.google.com/presentation/d/17_A_BH-sARkvC3qeYKFejE_bnlh__eXU/edit?usp=sharing&ouid=115990634876478916795&rtpof=true&sd=true)
- [Singly Linked List Sample Code](https://github.com/CISC2200-Fall-24-Fordham/SLList)
  - [Rule of Three](https://www.codementor.io/@sandesh87/the-rule-of-five-in-c-1pdgpzb04f)
  - [Class Templates](https://cplusplus.com/doc/tutorial/templates/#class_templates)
- Suggested Reading:
  - [Return by Reference](https://www.scaler.com/topics/cpp-return-reference/)
  - [C++ Compiler Support](https://en.cppreference.com/w/cpp/compiler_support)
  - [A simpler Makefile tutorial](https://codingnest.com/basic-makefiles/)

### Due

#### Today

- [Lab 1: IntArray](https://github.com/CISC2200-Fall-24-Fordham/Lab1) - due at midnight EST

#### Next Session / Upcoming

- Quiz 1 Test corrections due Wednesday 09/25
- Lab2 will be assigned next session
- Project part 1 will be assigned next session

## 09/23

### Content

- [Quiz 1 Results](./quiz/1/index.qmd)
- [SLList Slides II](https://docs.google.com/presentation/d/1wUVNy2AEawiv5mm2-2GzppNAfelU__0i/edit?usp=sharing&ouid=115990634876478916795&rtpof=true&sd=true)
- [Singly Linked List Sample Code II](https://github.com/CISC2200-Fall-24-Fordham/SLList-2)
  - [Rule of Three](https://www.codementor.io/@sandesh87/the-rule-of-five-in-c-1pdgpzb04f)
  - [Class Templates](https://cplusplus.com/doc/tutorial/templates/#class_templates)

### Lab / Project

- [Lab 2: Singly Linked Lists - due 10/02](https://github.com/CISC2200-Fall-24-Fordham/Lab2)
- [Project Part 1 - due 10/13](https://github.com/CISC2200-Fall-24-Fordham/Proj-1)
  - [Project: Simple Expression Evaluator Overview](https://docs.google.com/presentation/d/19jkySeLhxxQ9n7AQXN3KEHtNo26_Grhy/edit?usp=sharing&ouid=115990634876478916795&rtpof=true&sd=true)
  - [Part 1 Instructions](https://cisc2200.github.io/proj-part1/)

### Due

#### Next Session / Upcoming

- Quiz 1 test corrections due Wednesday 09/25
  - Email me the corrections
  - Email me about clarifications on the quiz
  - Email me about Lab1 0/30
- [Lab 2: Singly Linked Lists - due 10/02](https://github.com/CISC2200-Fall-24-Fordham/Lab2)
- [Project Part 1 - due 10/13](https://github.com/CISC2200-Fall-24-Fordham/Proj-1)
- [Quiz 2: 10/07 - study guide](https://docs.google.com/document/d/1dVEw0T5rDCFaZVHMhvZyIxU9wxyIHNNvcNlDyvCK7qM/edit?usp=sharing)

## 09/25

### Content

- [Singly Linked List Sample Code II](https://github.com/CISC2200-Fall-24-Fordham/SLList-2)
  - [Custom Iterators](https://www.internalpointers.com/post/writing-custom-iterators-modern-cpp)
- [Rule of Three](https://www.codementor.io/@sandesh87/the-rule-of-five-in-c-1pdgpzb04f)
  - Copy assignment vs. copy constructor (lets implement copy assignment)
  - Do we need a destructor for our node class?
- [Doubly Linked List Slides](https://docs.google.com/presentation/d/1DLrlCbtJjImK8KRjjH3Xx9WBPciODBAl/edit?usp=sharing&ouid=115990634876478916795&rtpof=true&sd=true)

#### Aside

- C++ is difficult because there are so many ways to do things
  - Standard Library:
    - [STL](https://en.cppreference.com/w/cpp/header)
    - [STL Algorithms](https://en.cppreference.com/w/cpp/algorithm)
    - [STL Containers](https://en.cppreference.com/w/cpp/container)
    - Other Third Party Libraries like [Boost](https://www.boost.org/)
  - Build Systems:
    - [CMake](https://cmake.org/features/)
    - [Make](https://www.gnu.org/software/make/)
    - [Bazel](https://bazel.build/)
    - [Meson](https://mesonbuild.com/)
    - [Ninja](https://ninja-build.org/)
    - [Spack](https://spack.io/)
  - Testing Libraries
    - [Google Test](https://github.com/google/googletest)
    - [DocTest](https://github.com/doctest/doctest)
    - [Catch2](https://github.com/catchorg/Catch2)
    - [CTest](https://cmake.org/cmake/help/latest/manual/ctest.1.html)
  - Benchmarking libraries
    - [Google Benchmark](https://github.com/google/benchmark)
    - [NanoBench](https://nanobench.ankerl.com/)
  - Profiling / debugging tools
    - [Valgrind](http://valgrind.org/)
    - [GDB](https://www.gnu.org/software/gdb/)
    - [LLDB](https://lldb.llvm.org/)
    - [Intel VTune](https://software.intel.com/content/www/us/en/develop/tools/oneapi/components/vtune-profiler.html)
  - Documentation Generators:
    - [Doxygen](https://www.doxygen.nl/index.html)
    - [Sphinx](https://www.sphinx-doc.org/en/master/)
  - Compiler variations:
    - [GNU C Compiler](https://gcc.gnu.org/)
    - [Clang](https://clang.llvm.org/)
    - [Visual Studio](https://visualstudio.microsoft.com/)
    - [Intel C++ Compiler](https://software.intel.com/content/www/us/en/develop/tools/oneapi/components/compiler.html)
  - IDEs:
    - [Visual Studio Code](https://code.visualstudio.com/)
    - [CLion](https://www.jetbrains.com/clion/)
    - [Eclipse](https://www.eclipse.org/)
    - [XCode](https://developer.apple.com/xcode/)

### Due

#### Next Session / Upcoming

- [Lab 2: Singly Linked Lists - due 10/02](https://github.com/CISC2200-Fall-24-Fordham/Lab2)
- [Project Part 1 - due 10/13](https://github.com/CISC2200-Fall-24-Fordham/Proj-1)
- [Quiz 2: 10/07 - study guide](https://docs.google.com/document/d/1dVEw0T5rDCFaZVHMhvZyIxU9wxyIHNNvcNlDyvCK7qM/edit?usp=sharing)

## 09/30

### Content

- [Doubly Linked List Slides](https://docs.google.com/presentation/d/1DLrlCbtJjImK8KRjjH3Xx9WBPciODBAl/edit?usp=sharing&ouid=115990634876478916795&rtpof=true&sd=true)
- [DLList Sample Code](https://github.com/CISC2200-Fall-24-Fordham/DLList)
- [What is the C / C++ Standard Library?](https://www.internalpointers.com/post/c-c-standard-library)
- Rule of Five (BONUS):
  - [Move Constructor Confusion](https://stackoverflow.com/questions/27497830/move-constructor-and-stdmove-confusion)
  - [Understanding lvalues and rvalues](https://www.internalpointers.com/post/understanding-meaning-lvalues-and-rvalues-c)
  - [Move Semantics for beginners](https://www.internalpointers.com/post/c-rvalue-references-and-move-semantics-beginners)
  - [Smart Pointers](https://www.internalpointers.com/post/beginner-s-look-smart-pointers-modern-c)

### Due

#### Next Session / Upcoming

- [Lab 2: Singly Linked Lists - due 10/02](https://github.com/CISC2200-Fall-24-Fordham/Lab2)
- [Project Part 1 - due 10/13](https://github.com/CISC2200-Fall-24-Fordham/Proj-1)
- [Quiz 2: 10/07 - study guide](https://docs.google.com/document/d/1dVEw0T5rDCFaZVHMhvZyIxU9wxyIHNNvcNlDyvCK7qM/edit?usp=sharing)

## 10/02

### Content

- [AList Implementation, Dynamic resizing](https://docs.google.com/presentation/d/1kGW3fz27YXg_aBXtlU3FH5h218POvAk0/edit?usp=sharing&ouid=115990634876478916795&rtpof=true&sd=true)
- [AList Sample Code](https://github.com/CISC2200-Fall-24-Fordham/AList)
- [Lab3: Array List - due 10/16](https://github.com/CISC2200-Fall-24-Fordham/Lab3)
- BONUS:
  - [Code Review of modern Vector Implementation](https://codereview.stackexchange.com/questions/116377/vector-implementation-c)
  - [When to use arrays vs. vectors vs. lists](https://www.reddit.com/r/cpp_questions/comments/5lqm5w/when_to_use_arrays_vs_vectors_vs_lists/)
  - [Are Lists Evil?](https://isocpp.org/blog/2014/06/stroustrup-lists)
  - [Big O Notation CheatSheet](https://bigocheatsheet.com/)

### Due

#### Today

- [Lab 2: Singly Linked Lists - due midnight EST](https://github.com/CISC2200-Fall-24-Fordham/Lab2)

#### Next Session / Upcoming

- [Project Part 1 - due 10/13](https://github.com/CISC2200-Fall-24-Fordham/Proj-1)
- [Quiz 2: 10/07 - study guide](https://docs.google.com/document/d/1dVEw0T5rDCFaZVHMhvZyIxU9wxyIHNNvcNlDyvCK7qM/edit?usp=sharing)
- [Lab3: Array List - due 10/16](https://github.com/CISC2200-Fall-24-Fordham/Lab3)

## 10/07

- **QUIZ 2** given in class

### Due

#### Next Session / Upcoming

- [Project Part 1 - due 10/13](https://github.com/CISC2200-Fall-24-Fordham/Proj-1)
  - [Part 1 Instructions](https://cisc2200.github.io/proj-part1/)
- [Lab3: Array List - due 10/16](https://github.com/CISC2200-Fall-24-Fordham/Lab3)
- [Quiz 3: 10/21 - study guide](https://docs.google.com/document/d/14wCUimC5R58kmr0A43jllbdcgqITEk18t9wb5H93zUw/edit?usp=sharing)

## 10/09

### Content

- [Inheritance](https://docs.google.com/presentation/d/1hajhN4wtebvWHZ1C0KN3ETvk92TYycap/edit?usp=sharing&ouid=115990634876478916795&rtpof=true&sd=true)
- [Stacks](https://docs.google.com/presentation/d/1_wqD17OjCP33Jk66IM9tS-5kGfwq8D4V/edit?usp=sharing&ouid=115990634876478916795&rtpof=true&sd=true)
- [Recursion](https://docs.google.com/presentation/d/1YN2__DwgsPFejUZ0AjfPHkwnsqCHhJC6/edit?usp=sharing&ouid=115990634876478916795&rtpof=true&sd=true)
- Quiz 3 review
  - [Quiz 3: 10/21 - study guide](https://docs.google.com/document/d/14wCUimC5R58kmr0A43jllbdcgqITEk18t9wb5H93zUw/edit?usp=sharing)

#### Bonus Content

- LeetCode Practice **easy**
  - [Baseball game](https://leetcode.com/problems/baseball-game/description/)
  - [Palindrome Linked List](https://leetcode.com/problems/palindrome-linked-list/)
  - [Valid Parentheses](https://leetcode.com/problems/valid-parentheses/)
- LeetCode Practice **medium**
  - [Evaluate Reverse Polish Notation](https://leetcode.com/problems/evaluate-reverse-polish-notation/)
  - [Flatten Nested List Iterator](https://leetcode.com/problems/flatten-nested-list-iterator/)
- LeetCode Practice **hard**
  - [Maximum Score of a Good Subarray](https://leetcode.com/problems/maximum-score-of-a-good-subarray/)
  - [Find Buildings where Alice and Bob can meet](https://leetcode.com/problems/find-building-where-alice-and-bob-can-meet/description/)
- Supplemental Reading
  - [MSFT Inheritance in C++](https://learn.microsoft.com/en-us/cpp/cpp/inheritance-cpp?view=msvc-170)
  - [Bags, Queues and Stacks](https://algs4.cs.princeton.edu/13stacks/) - over 60 practice exercises!
  - [Stack and Heap Memory](https://courses.grainger.illinois.edu/cs225/fa2022/resources/stack-heap/)
  - [Recursion](https://jeffe.cs.illinois.edu/teaching/algorithms/book/01-recursion.pdf) - 70 pages...
  - [Recursion 101 from Medium](https://betterprogramming.pub/recursion-101-a5e18158c66f)

### Due

#### Next Session / Upcoming

- [Project Part 1 - due 10/13](https://github.com/CISC2200-Fall-24-Fordham/Proj-1)
- [Lab3: Array List - due 10/16](https://github.com/CISC2200-Fall-24-Fordham/Lab3)
- [Quiz 3: 10/21 - study guide](https://docs.google.com/document/d/14wCUimC5R58kmr0A43jllbdcgqITEk18t9wb5H93zUw/edit?usp=sharing)

## **COLUMBUS DAY**

## 10/16

### Content

- Quiz 1 and Quiz 2 review
- Project Part 2 - due 11/15
- DLL and Array Review
- Quiz 3 review
  - [Quiz 3: 10/21 - study guide](https://docs.google.com/document/d/14wCUimC5R58kmr0A43jllbdcgqITEk18t9wb5H93zUw/edit?usp=sharing)

### Lab / Project

### Due

#### Today

- [Lab3: Array List - due midnight EST](https://github.com/CISC2200-Fall-24-Fordham/Lab3)

#### Next Session / Upcoming

- [Quiz 3: 10/21 - study guide](https://docs.google.com/document/d/14wCUimC5R58kmr0A43jllbdcgqITEk18t9wb5H93zUw/edit?usp=sharing)
- [Project Part 2 - due 11/15](https://github.com/CISC2200-Fall-24-Fordham/Proj-2)

## 10/21

- **QUIZ 3** given in class

### Lab / Project

### Due

#### Today

#### Next Session / Upcoming

- [Project Part 2 - due 11/15](https://github.com/CISC2200-Fall-24-Fordham/Proj-2)

## 10/23

### Content

- Quiz Review
  - [Quiz 1 Study Guide](https://docs.google.com/document/d/1hzwxkHhTrzqFQrr6YJNpGAaOq11AjvNoqIYvWn3NaEI/edit?usp=sharing)
  - [Quiz 2 Study Guide](https://docs.google.com/document/d/1dVEw0T5rDCFaZVHMhvZyIxU9wxyIHNNvcNlDyvCK7qM/edit?usp=sharing)
  - [Quiz 3 Study Guide](https://docs.google.com/document/d/14wCUimC5R58kmr0A43jllbdcgqITEk18t9wb5H93zUw/edit?usp=sharing)
- Lab Review
- Midterm review
  - Kahoot!

### Lab / Project

### Due

#### Today

#### Next Session / Upcoming

- [Project Part 2 - due 11/15](https://github.com/CISC2200-Fall-24-Fordham/Proj-2)

## 10/28

- **MIDTERM**

### Due

#### Next Session / Upcoming

- [Project Part 2 - due 11/15](https://github.com/CISC2200-Fall-24-Fordham/Proj-2)
- 10/29: Mid-semester evaluations due

## 10/30

### Content

- [Play Guess My Number](https://www.mathsisfun.com/games/guess_number.html)
- [Sorted Lists Slides](https://docs.google.com/presentation/d/1qi1sidb5D85LXXlFwV3R_XnHnM05uaiX/edit?usp=sharing&ouid=115990634876478916795&rtpof=true&sd=true)
- [Sorted List Wikipedia](https://en.wikipedia.org/wiki/Sorted_array)
- Searching Algorithms:
  - [Linear Search](https://en.wikipedia.org/wiki/Linear_search)
  - [Binary Search](https://en.wikipedia.org/wiki/Binary_search)
  - [Fibonacci Search](https://en.wikipedia.org/wiki/Fibonacci_search_technique)

### Lab / Project

- [Lab 5: Sorted Lists - due 11/06](https://github.com/CISC2200-Fall-24-Fordham/Lab5)

### Due

#### Next Session / Upcoming

- [Lab 5: Sorted Lists - due 11/06](https://github.com/CISC2200-Fall-24-Fordham/Lab5)
- 11/04: Round 2 attendance reports due
- [Project Part 2 - due 11/15](https://github.com/CISC2200-Fall-24-Fordham/Proj-2)

## 11/04

### Content

- [Sets, Iterators and Sorting Slides](https://docs.google.com/presentation/d/1jujWropUdrrLmhRjjOPB1vtCgHRIxrFb/edit?usp=sharing&ouid=115990634876478916795&rtpof=true&sd=true)
- [Sorting Algorithm Wikipedia](https://en.wikipedia.org/wiki/Sorting_algorithm)
- [Shuffling Algorithms Wikipedia](https://en.wikipedia.org/wiki/Shuffling#Algorithms)
- What happens when we only have limited comparisons? (Related algorithms)
  - [Ranking (information retrieval)](https://en.wikipedia.org/wiki/Ranking_(information_retrieval))
  - [Machine Learned Ranking (MLR)](https://en.wikipedia.org/wiki/Learning_to_rank)
  - [Semantic Search](https://en.wikipedia.org/wiki/Semantic_search)
  - [Tournaments](https://en.wikipedia.org/wiki/Tournament), fairness, and [Tournament Selection](https://en.wikipedia.org/wiki/Tournament_selection)
  - [Elo rating system](https://en.wikipedia.org/wiki/Elo_rating_system)
  - [Electoral Systems](https://en.wikipedia.org/wiki/Electoral_system)

### Lab / Project

### Due

#### Today

- Late Semester Student Attendance due

#### Next Session / Upcoming

- 11/05: Vote!!!
- [Lab 5: Sorted Lists - due 11/06](https://github.com/CISC2200-Fall-24-Fordham/Lab5)
- [Project Part 2 - due 11/15](https://github.com/CISC2200-Fall-24-Fordham/Proj-2)

## 11/06

### Content

- [Binary Search Trees and Maps](https://docs.google.com/presentation/d/1Fg5r9bJvHLRRXjv8BDDv2zpAAVqF6Cce/edit?usp=sharing&ouid=115990634876478916795&rtpof=true&sd=true) - try commenting on the slides!
- [The Art of Computer Programming: pp 298-305, 308-316](https://drive.google.com/file/d/1Y3fU8XSsneBmjq4d1OMNU_z9agB4epwU/view?usp=sharing)
  - [Orthogonal Lists OneNote](https://1drv.ms/o/c/4ef2e1eeb9fc1907/EiYfjzgcrHBPgUG_jLXZ1eEB0kGwqaLUcA2AVup58ne2Cw)
  - [Trees OneNote](https://1drv.ms/o/c/4ef2e1eeb9fc1907/EiYfjzgcrHBPgUG_jLXZ1eEB0kGwqaLUcA2AVup58ne2Cw)

Wikipedia links / rabbit hole:
- [List of Data Structures](https://en.wikipedia.org/wiki/List_of_data_structures)

### Due

#### Today

- [Lab 5: Sorted Lists - due 11/06](https://github.com/CISC2200-Fall-24-Fordham/Lab5)

#### Next Session / Upcoming

- [Project Part 2 - due 11/15](https://github.com/CISC2200-Fall-24-Fordham/Proj-2)

## 11/11

### Content

- BST and Maps in-class Lab

### Lab / Project

### Due

#### Today

#### Next Session / Upcoming

- [Project Part 2 - due 11/15](https://github.com/CISC2200-Fall-24-Fordham/Proj-2)

## 11/13

### Content

- Runtime Analysis (Big O Notation)
- BST Performance

### Lab / Project

### Due

#### Today

#### Next Session / Upcoming

- [Project Part 2 - due 11/15](https://github.com/CISC2200-Fall-24-Fordham/Proj-2)

## 11/18

### Content

- Hashing

### Lab / Project

### Due

#### Today

#### Next Session / Upcoming

## 11/20

### Content

- Heaps and Priority Queues

### Lab / Project

### Due

#### Today

#### Next Session / Upcoming

## 11/25

### Content

- Tree/Graph Representations and Traversals

### Lab / Project

### Due

#### Today

#### Next Session / Upcoming

## **THANKSGIVING**

## 12/02

### Content

- Graph Algorithms Part II

### Lab / Project

### Due

#### Today

- Last day for designating a course Pass/Fail
- Last day to withdraw from a course without incurring a WF

#### Next Session / Upcoming

## 12/04

### Content

- Final Review Part I
- Extra content Part I

### Lab / Project

### Due

#### Today

#### Next Session / Upcoming

## 12/09

### Content

- Final Review Part II
- Extra content Part II

### Lab / Project

### Due

#### Today

#### Next Session / Upcoming

- 12/10: Last Day of Classes...

## 12/11

*Make up day in case of cancellations...*

## **FINAL EXAMS!**

- Your grade will be posted within three days of the final exam
