---
# yamllint disable rule:line-length
name: Documentation Publish

"on":
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cameronrutherford/quarto-ci@sha256:e711e6271819961e0ab79265da7eed0f16c42803eda87e6155eea8f164f31477
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Quarto Render
        run: quarto render

      - name: Quarto Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          render: false
          target: quarto-pub
          QUARTO_PUB_AUTH_TOKEN: ${{ secrets.QUARTO_PUB_TOKEN }}
