---
name: Documentation Publish

"on":
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cameronrutherford/quarto-ci
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Quarto Render
        run: |
          quarto render
          ls -al ./docs
      - name: Setup SSH keys
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ../private.key
          sudo chmod 600 ../private.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
      - name: Deploy site
        env:
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key
        run: |
          scp -v -r -i $SSH_KEY_PATH \
            -o GlobalKnownHostsFile=~/.ssh/known_hosts docs \
            rrutherford4@erdos.dsm.fordham.edu:~/public_html
